# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7,7)
print(x)

tensor([[0.6434, 0.9146, 0.8489, 0.2639, 0.7005, 0.9013, 0.4543],
        [0.5758, 0.7188, 0.3841, 0.0300, 0.3341, 0.9438, 0.1437],
        [0.4009, 0.6552, 0.1191, 0.5179, 0.3018, 0.4889, 0.0631],
        [0.3025, 0.2670, 0.7639, 0.1540, 0.8180, 0.9871, 0.1969],
        [0.4072, 0.3154, 0.0250, 0.2065, 0.4069, 0.1961, 0.8352],
        [0.7806, 0.0409, 0.8697, 0.8513, 0.9857, 0.8336, 0.8977],
        [0.2936, 0.5850, 0.8513, 0.6044, 0.8860, 0.0377, 0.5629]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
y = torch.rand(1,7)

# Perform matrix multiplication 
torch.matmul(x, y.T)

tensor([[1.4638],
        [1.0069],
        [0.9589],
        [0.8953],
        [0.7612],
        [1.5068],
        [1.1576]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
RANDOM_SEED = 0


# Create two random tensors
torch.manual_seed(RANDOM_SEED)
x= torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
y = torch.rand(1,7)

# Matrix multiply tensors
new = torch.matmul(x,y.T)
new, new.size()


(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
RANDOM_SEED = 1234
torch.cuda.random.seed(RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# Set random seed
RANDOM_SEED = 1234

# Check for access to GPU
torch.cuda.is_available()

# Create two random tensors on GPU
x = torch.rand(2,3, device="cuda")
y = torch.rand(2,3, device="cuda")

x, y

(tensor([[0.0194, 0.7733, 0.8650],
         [0.8097, 0.6666, 0.3653]], device='cuda:0'),
 tensor([[0.7874, 0.1344, 0.2190],
         [0.8193, 0.6969, 0.7304]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B

new = torch.matmul(x,y.T)


tensor([[0.3087, 1.1867],
        [0.8071, 1.3947]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [13]:
# Find max
torch.max(new)

# Find min
torch.min(new)

tensor(0.8279)

### 9. Find the maximum and minimum index values of the output of 7.

In [14]:
# Find arg max
new.argmin()
# Find arg min
new.argmax()

tensor(3)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [16]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

# Create random tensor
x = torch.rand(1,1,1,10)

# Remove single dimensions
y = torch.squeeze(x)

# Print out tensors and their shapes
x, x.size(), y, y.size()

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))